#!/bin/bash

echo "Compiling Util"
cd ../cpp/Util
make clean
rm libUtil.*
rm .qmake.stash
qmake Util.pro
make -j10

echo "Compiling Server"
cd ../../Server
make clean
rm CMakeCache.txt
rm ./runServer
cmake CMakeLists.txt
make -j10
